//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int AdministratorId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumDodavanja { get; set; }
        public int KorisnickiNalogId { get; set; }
        public int KontaktInfoId { get; set; }
    
        public virtual KontaktInfo KontaktInfo { get; set; }
        public virtual KorisnickiNalog KorisnickiNalog { get; set; }
    }
}
