//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TutorEntities : DbContext
    {
        public TutorEntities()
            : base("name=TutorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Grad> Grads { get; set; }
        public virtual DbSet<KontaktInfo> KontaktInfoes { get; set; }
        public virtual DbSet<KorisnickiNalog> KorisnickiNalogs { get; set; }
        public virtual DbSet<Materijal> Materijals { get; set; }
        public virtual DbSet<NivoTezine> NivoTezines { get; set; }
        public virtual DbSet<ObimStudent> ObimStudents { get; set; }
        public virtual DbSet<Oblast> Oblasts { get; set; }
        public virtual DbSet<OcjenaStudent> OcjenaStudents { get; set; }
        public virtual DbSet<OcjenaTutor> OcjenaTutors { get; set; }
        public virtual DbSet<Podkategorija> Podkategorijas { get; set; }
        public virtual DbSet<Prijava> Prijavas { get; set; }
        public virtual DbSet<RadnoStanje> RadnoStanjes { get; set; }
        public virtual DbSet<Spol> Spols { get; set; }
        public virtual DbSet<StatusKorisnickogRacuna> StatusKorisnickogRacunas { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Termin> Termins { get; set; }
        public virtual DbSet<TipStudenta> TipStudentas { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
        public virtual DbSet<TutorTitula> TutorTitulas { get; set; }
        public virtual DbSet<Ucionica> Ucionicas { get; set; }
        public virtual DbSet<Zahtjev> Zahtjevs { get; set; }
        public virtual DbSet<BanPrijavaStudent> BanPrijavaStudents { get; set; }
        public virtual DbSet<BanPrijavaTutor> BanPrijavaTutors { get; set; }
        public virtual DbSet<TerminCasa> TerminCasas { get; set; }
    
        public virtual int tsp_Administrator_Insert(string ime, string prezime, Nullable<System.DateTime> datumDodavanja, string email, string telefon, string korisnickoIme, string lozinkaHash, string lozinkaSalt)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var datumDodavanjaParameter = datumDodavanja.HasValue ?
                new ObjectParameter("DatumDodavanja", datumDodavanja) :
                new ObjectParameter("DatumDodavanja", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsp_Administrator_Insert", imeParameter, prezimeParameter, datumDodavanjaParameter, emailParameter, telefonParameter, korisnickoImeParameter, lozinkaHashParameter, lozinkaSaltParameter);
        }
    
        public virtual ObjectResult<Administrator_SelectAll> tsp_Administrator_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Administrator_SelectAll>("tsp_Administrator_SelectAll");
        }
    
        public virtual ObjectResult<Administrator_NameSelect> tsp_Administrator_SelectByImePrezime(string imePrezime)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Administrator_NameSelect>("tsp_Administrator_SelectByImePrezime", imePrezimeParameter);
        }
    
        public virtual ObjectResult<Administrator_SelectOne> tsp_Administrator_SelectOne(Nullable<int> administratorId)
        {
            var administratorIdParameter = administratorId.HasValue ?
                new ObjectParameter("AdministratorId", administratorId) :
                new ObjectParameter("AdministratorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Administrator_SelectOne>("tsp_Administrator_SelectOne", administratorIdParameter);
        }
    
        public virtual int tsp_Administrator_Update(Nullable<int> administratorId, string ime, string prezime, string email, string telefon, string korisnickoIme, string lozinkaHash, string lozinkaSalt)
        {
            var administratorIdParameter = administratorId.HasValue ?
                new ObjectParameter("AdministratorId", administratorId) :
                new ObjectParameter("AdministratorId", typeof(int));
    
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsp_Administrator_Update", administratorIdParameter, imeParameter, prezimeParameter, emailParameter, telefonParameter, korisnickoImeParameter, lozinkaHashParameter, lozinkaSaltParameter);
        }
    
        public virtual ObjectResult<Grad_Result> tsp_Grad_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Grad_Result>("tsp_Grad_SelectAll");
        }
    
        public virtual ObjectResult<Tutor_SearchSelect_Result> tps_Tutor_SearchSelect(string imePrezime, Nullable<int> gradId, Nullable<int> oblastId)
        {
            var imePrezimeParameter = imePrezime != null ?
                new ObjectParameter("ImePrezime", imePrezime) :
                new ObjectParameter("ImePrezime", typeof(string));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var oblastIdParameter = oblastId.HasValue ?
                new ObjectParameter("OblastId", oblastId) :
                new ObjectParameter("OblastId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SearchSelect_Result>("tps_Tutor_SearchSelect", imePrezimeParameter, gradIdParameter, oblastIdParameter);
        }
    
        public virtual ObjectResult<Tutor_Details_Result> tsp_Tutor_Details(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_Details_Result>("tsp_Tutor_Details", idParameter);
        }
    
        public virtual ObjectResult<Oblast_select_Result> tps_Oblast_select(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Oblast_select_Result>("tps_Oblast_select", idParameter);
        }
    
        public virtual ObjectResult<Zahtjev_SelectByTutorId_Result> tps_Zahtjev_SelectByTutorId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zahtjev_SelectByTutorId_Result>("tps_Zahtjev_SelectByTutorId", idParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectTutorUcionica_Result> tsp_Ucionica_SelectTutorUcionica(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectTutorUcionica_Result>("tsp_Ucionica_SelectTutorUcionica", idParameter);
        }
    
        public virtual ObjectResult<Tutor_ReviewsSelect_Result> tsp_Tutor_ReviewsSelect(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_ReviewsSelect_Result>("tsp_Tutor_ReviewsSelect", idParameter);
        }
    
        public virtual ObjectResult<Tutor_SelectAll_Result> tsp_Tutor_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SelectAll_Result>("tsp_Tutor_SelectAll");
        }
    
        public virtual ObjectResult<BanStudente_Select_Result> tsp_BanPrijavaStudente_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanStudente_Select_Result>("tsp_BanPrijavaStudente_Select");
        }
    
        public virtual ObjectResult<BanPrijavaStudente_SelectOne_Result> tsp_BanPrijavaStudente_SelectOne(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanPrijavaStudente_SelectOne_Result>("tsp_BanPrijavaStudente_SelectOne", idParameter);
        }
    
        public virtual ObjectResult<BanTutor_Select_Result> tsp_BanPrijavaTutor_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanTutor_Select_Result>("tsp_BanPrijavaTutor_Select");
        }
    
        public virtual ObjectResult<BanPrijavaTutor_SelectOne_Result> tsp_BanPrijavaTutor_SelectOne(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BanPrijavaTutor_SelectOne_Result>("tsp_BanPrijavaTutor_SelectOne", idParameter);
        }
    
        public virtual ObjectResult<Tutori_SelectBanTutor_Result> tsp_Tutori_SelectBanTutor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutori_SelectBanTutor_Result>("tsp_Tutori_SelectBanTutor");
        }
    
        public virtual ObjectResult<Student_BanStudents_Result> tsp_Student_SelectBanStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_BanStudents_Result>("tsp_Student_SelectBanStudents");
        }
    
        public virtual int tsp_Student_Insert(string ime, string prezime, Nullable<System.DateTime> datumRodjenja, Nullable<System.DateTime> datumDodavanja, string email, string telefon, string adresa, string korisnickoIme, string lozinkaHash, string lozinkaSalt, Nullable<int> spolId, Nullable<int> gradId, Nullable<int> tipStudentaId)
        {
            var imeParameter = ime != null ?
                new ObjectParameter("Ime", ime) :
                new ObjectParameter("Ime", typeof(string));
    
            var prezimeParameter = prezime != null ?
                new ObjectParameter("Prezime", prezime) :
                new ObjectParameter("Prezime", typeof(string));
    
            var datumRodjenjaParameter = datumRodjenja.HasValue ?
                new ObjectParameter("DatumRodjenja", datumRodjenja) :
                new ObjectParameter("DatumRodjenja", typeof(System.DateTime));
    
            var datumDodavanjaParameter = datumDodavanja.HasValue ?
                new ObjectParameter("DatumDodavanja", datumDodavanja) :
                new ObjectParameter("DatumDodavanja", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            var korisnickoImeParameter = korisnickoIme != null ?
                new ObjectParameter("KorisnickoIme", korisnickoIme) :
                new ObjectParameter("KorisnickoIme", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var spolIdParameter = spolId.HasValue ?
                new ObjectParameter("SpolId", spolId) :
                new ObjectParameter("SpolId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var tipStudentaIdParameter = tipStudentaId.HasValue ?
                new ObjectParameter("TipStudentaId", tipStudentaId) :
                new ObjectParameter("TipStudentaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsp_Student_Insert", imeParameter, prezimeParameter, datumRodjenjaParameter, datumDodavanjaParameter, emailParameter, telefonParameter, adresaParameter, korisnickoImeParameter, lozinkaHashParameter, lozinkaSaltParameter, spolIdParameter, gradIdParameter, tipStudentaIdParameter);
        }
    
        public virtual ObjectResult<Student_SearchSelect_Result> tsp_Student_SearchSelect(string imeprezime, Nullable<int> gradId)
        {
            var imeprezimeParameter = imeprezime != null ?
                new ObjectParameter("Imeprezime", imeprezime) :
                new ObjectParameter("Imeprezime", typeof(string));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_SearchSelect_Result>("tsp_Student_SearchSelect", imeprezimeParameter, gradIdParameter);
        }
    
        public virtual ObjectResult<Student_Details_Result> tsp_Student_Details(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_Details_Result>("tsp_Student_Details", idParameter);
        }
    
        public virtual ObjectResult<OcjenaStudent_SelectComments_Result> tsp_OcjenaStudent_SelectComments(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OcjenaStudent_SelectComments_Result>("tsp_OcjenaStudent_SelectComments", idParameter);
        }
    
        public virtual ObjectResult<Student_PohadajniPredmeti_Result> tsp_Student_PohadajniPredmeti(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_PohadajniPredmeti_Result>("tsp_Student_PohadajniPredmeti", idParameter);
        }
    
        public virtual ObjectResult<Student_SelectUcionice_Result> tsp_Student_SelectUcionice(Nullable<int> studentId)
        {
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("StudentId", studentId) :
                new ObjectParameter("StudentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_SelectUcionice_Result>("tsp_Student_SelectUcionice", studentIdParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectActive_Result> tsp_Ucionica_SelectActive(Nullable<int> oblastId, Nullable<int> gradId)
        {
            var oblastIdParameter = oblastId.HasValue ?
                new ObjectParameter("OblastId", oblastId) :
                new ObjectParameter("OblastId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectActive_Result>("tsp_Ucionica_SelectActive", oblastIdParameter, gradIdParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectStaro_Result> tsp_Ucionica_SelectStaro(Nullable<int> oblastId, Nullable<int> gradId)
        {
            var oblastIdParameter = oblastId.HasValue ?
                new ObjectParameter("OblastId", oblastId) :
                new ObjectParameter("OblastId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectStaro_Result>("tsp_Ucionica_SelectStaro", oblastIdParameter, gradIdParameter);
        }
    
        public virtual ObjectResult<Ucionica_Details_Result> tsp_Ucionica_Details(Nullable<int> ucionicaId)
        {
            var ucionicaIdParameter = ucionicaId.HasValue ?
                new ObjectParameter("UcionicaId", ucionicaId) :
                new ObjectParameter("UcionicaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_Details_Result>("tsp_Ucionica_Details", ucionicaIdParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectUcenici_Result> tsp_Ucionica_SelectUcenici(Nullable<int> ucionicaid)
        {
            var ucionicaidParameter = ucionicaid.HasValue ?
                new ObjectParameter("Ucionicaid", ucionicaid) :
                new ObjectParameter("Ucionicaid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectUcenici_Result>("tsp_Ucionica_SelectUcenici", ucionicaidParameter);
        }
    
        public virtual ObjectResult<Predmet_Report_Result> tps_Predmet_Report(Nullable<int> gradId, Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo)
        {
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("DatumOd", datumOd) :
                new ObjectParameter("DatumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("DatumDo", datumDo) :
                new ObjectParameter("DatumDo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Predmet_Report_Result>("tps_Predmet_Report", gradIdParameter, datumOdParameter, datumDoParameter);
        }
    
        public virtual ObjectResult<Tutor_SelectBest_Result> tsp_Tutor_SelectBest(Nullable<int> gradId, Nullable<int> oblastId, Nullable<System.DateTime> datumOd, Nullable<System.DateTime> datumDo)
        {
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var oblastIdParameter = oblastId.HasValue ?
                new ObjectParameter("OblastId", oblastId) :
                new ObjectParameter("OblastId", typeof(int));
    
            var datumOdParameter = datumOd.HasValue ?
                new ObjectParameter("DatumOd", datumOd) :
                new ObjectParameter("DatumOd", typeof(System.DateTime));
    
            var datumDoParameter = datumDo.HasValue ?
                new ObjectParameter("DatumDo", datumDo) :
                new ObjectParameter("DatumDo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SelectBest_Result>("tsp_Tutor_SelectBest", gradIdParameter, oblastIdParameter, datumOdParameter, datumDoParameter);
        }
    
        public virtual ObjectResult<Tutor_UpdateSelect_Result> tsp_Tutor_UpdateSelect(Nullable<int> tutorId)
        {
            var tutorIdParameter = tutorId.HasValue ?
                new ObjectParameter("tutorId", tutorId) :
                new ObjectParameter("tutorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_UpdateSelect_Result>("tsp_Tutor_UpdateSelect", tutorIdParameter);
        }
    
        public virtual int tsp_Tutor_Update(Nullable<int> tutuorId, Nullable<int> gradId, Nullable<int> radnoStanjeId, Nullable<int> tutorTitulaId, Nullable<int> podKategorijaId, string nazivUstanove, Nullable<double> cijenaCasA, byte[] tutorTumbnail, byte[] tutorSlika, string lozinkaSalt, string lozinkaHash, string email, string telefon, string adresa)
        {
            var tutuorIdParameter = tutuorId.HasValue ?
                new ObjectParameter("TutuorId", tutuorId) :
                new ObjectParameter("TutuorId", typeof(int));
    
            var gradIdParameter = gradId.HasValue ?
                new ObjectParameter("GradId", gradId) :
                new ObjectParameter("GradId", typeof(int));
    
            var radnoStanjeIdParameter = radnoStanjeId.HasValue ?
                new ObjectParameter("RadnoStanjeId", radnoStanjeId) :
                new ObjectParameter("RadnoStanjeId", typeof(int));
    
            var tutorTitulaIdParameter = tutorTitulaId.HasValue ?
                new ObjectParameter("TutorTitulaId", tutorTitulaId) :
                new ObjectParameter("TutorTitulaId", typeof(int));
    
            var podKategorijaIdParameter = podKategorijaId.HasValue ?
                new ObjectParameter("PodKategorijaId", podKategorijaId) :
                new ObjectParameter("PodKategorijaId", typeof(int));
    
            var nazivUstanoveParameter = nazivUstanove != null ?
                new ObjectParameter("NazivUstanove", nazivUstanove) :
                new ObjectParameter("NazivUstanove", typeof(string));
    
            var cijenaCasAParameter = cijenaCasA.HasValue ?
                new ObjectParameter("CijenaCasA", cijenaCasA) :
                new ObjectParameter("CijenaCasA", typeof(double));
    
            var tutorTumbnailParameter = tutorTumbnail != null ?
                new ObjectParameter("TutorTumbnail", tutorTumbnail) :
                new ObjectParameter("TutorTumbnail", typeof(byte[]));
    
            var tutorSlikaParameter = tutorSlika != null ?
                new ObjectParameter("TutorSlika", tutorSlika) :
                new ObjectParameter("TutorSlika", typeof(byte[]));
    
            var lozinkaSaltParameter = lozinkaSalt != null ?
                new ObjectParameter("LozinkaSalt", lozinkaSalt) :
                new ObjectParameter("LozinkaSalt", typeof(string));
    
            var lozinkaHashParameter = lozinkaHash != null ?
                new ObjectParameter("LozinkaHash", lozinkaHash) :
                new ObjectParameter("LozinkaHash", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telefonParameter = telefon != null ?
                new ObjectParameter("Telefon", telefon) :
                new ObjectParameter("Telefon", typeof(string));
    
            var adresaParameter = adresa != null ?
                new ObjectParameter("Adresa", adresa) :
                new ObjectParameter("Adresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tsp_Tutor_Update", tutuorIdParameter, gradIdParameter, radnoStanjeIdParameter, tutorTitulaIdParameter, podKategorijaIdParameter, nazivUstanoveParameter, cijenaCasAParameter, tutorTumbnailParameter, tutorSlikaParameter, lozinkaSaltParameter, lozinkaHashParameter, emailParameter, telefonParameter, adresaParameter);
        }
    
        public virtual ObjectResult<Zahtjev_SelectUnread_Result> tsp_Zahtjev_SelectUnread(Nullable<int> tutorId)
        {
            var tutorIdParameter = tutorId.HasValue ?
                new ObjectParameter("TutorId", tutorId) :
                new ObjectParameter("TutorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zahtjev_SelectUnread_Result>("tsp_Zahtjev_SelectUnread", tutorIdParameter);
        }
    
        public virtual ObjectResult<Zahtjev_SelectDetail_Result> tsp_Zahtjev_SelectDetail(Nullable<int> zahtjevId)
        {
            var zahtjevIdParameter = zahtjevId.HasValue ?
                new ObjectParameter("ZahtjevId", zahtjevId) :
                new ObjectParameter("ZahtjevId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zahtjev_SelectDetail_Result>("tsp_Zahtjev_SelectDetail", zahtjevIdParameter);
        }
    
        public virtual ObjectResult<TerminCas_SelectTermins_Result> tsp_TerminCas_SelectTermins(Nullable<int> tutuorId)
        {
            var tutuorIdParameter = tutuorId.HasValue ?
                new ObjectParameter("TutuorId", tutuorId) :
                new ObjectParameter("TutuorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TerminCas_SelectTermins_Result>("tsp_TerminCas_SelectTermins", tutuorIdParameter);
        }
    
        public virtual ObjectResult<Tutor_SelectTutorStudents_Result> tsp_Tutor_SelectTutorStudents(Nullable<int> tutorId)
        {
            var tutorIdParameter = tutorId.HasValue ?
                new ObjectParameter("TutorId", tutorId) :
                new ObjectParameter("TutorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SelectTutorStudents_Result>("tsp_Tutor_SelectTutorStudents", tutorIdParameter);
        }
    
        public virtual ObjectResult<Tutor_SelectActiveUcionica_Result> tsp_Tutor_SelectActiveUcionica(string naslov, Nullable<int> tutorid)
        {
            var naslovParameter = naslov != null ?
                new ObjectParameter("Naslov", naslov) :
                new ObjectParameter("Naslov", typeof(string));
    
            var tutoridParameter = tutorid.HasValue ?
                new ObjectParameter("Tutorid", tutorid) :
                new ObjectParameter("Tutorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SelectActiveUcionica_Result>("tsp_Tutor_SelectActiveUcionica", naslovParameter, tutoridParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectDetails_Result> tsp_Ucionica_SelectDetails(Nullable<int> ucionicaId)
        {
            var ucionicaIdParameter = ucionicaId.HasValue ?
                new ObjectParameter("UcionicaId", ucionicaId) :
                new ObjectParameter("UcionicaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectDetails_Result>("tsp_Ucionica_SelectDetails", ucionicaIdParameter);
        }
    
        public virtual ObjectResult<Prijave_SelectAccepted_Result> tsp_Prijave_SelectAccepted(Nullable<int> ucionicaId)
        {
            var ucionicaIdParameter = ucionicaId.HasValue ?
                new ObjectParameter("UcionicaId", ucionicaId) :
                new ObjectParameter("UcionicaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prijave_SelectAccepted_Result>("tsp_Prijave_SelectAccepted", ucionicaIdParameter);
        }
    
        public virtual ObjectResult<Ucionica_SelectNonActive_Result> tsp_Ucionica_SelectNonActive(string naslov, Nullable<int> tutorID)
        {
            var naslovParameter = naslov != null ?
                new ObjectParameter("Naslov", naslov) :
                new ObjectParameter("Naslov", typeof(string));
    
            var tutorIDParameter = tutorID.HasValue ?
                new ObjectParameter("TutorID", tutorID) :
                new ObjectParameter("TutorID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ucionica_SelectNonActive_Result>("tsp_Ucionica_SelectNonActive", naslovParameter, tutorIDParameter);
        }
    
        public virtual ObjectResult<Materijal_Select_Result> tsp_Materijal_Select(Nullable<int> ucionicaId)
        {
            var ucionicaIdParameter = ucionicaId.HasValue ?
                new ObjectParameter("UcionicaId", ucionicaId) :
                new ObjectParameter("UcionicaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Materijal_Select_Result>("tsp_Materijal_Select", ucionicaIdParameter);
        }
    
        public virtual ObjectResult<Prijava_SelectUcionica_Result> tsp_Prijava_SelectUcionica(Nullable<int> ucionicaId)
        {
            var ucionicaIdParameter = ucionicaId.HasValue ?
                new ObjectParameter("UcionicaId", ucionicaId) :
                new ObjectParameter("UcionicaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prijava_SelectUcionica_Result>("tsp_Prijava_SelectUcionica", ucionicaIdParameter);
        }
    
        public virtual ObjectResult<Tutor_SelectByOblast_Result> tsp_Tutor_SelectByOblast(Nullable<int> oblastId, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var oblastIdParameter = oblastId.HasValue ?
                new ObjectParameter("OblastId", oblastId) :
                new ObjectParameter("OblastId", typeof(int));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tutor_SelectByOblast_Result>("tsp_Tutor_SelectByOblast", oblastIdParameter, pageNumberParameter, pageSizeParameter);
        }
    }
}
