//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijava
    {
        public int PrijavaId { get; set; }
        public System.DateTime DatumPrijave { get; set; }
        public bool Prihvaceno { get; set; }
        public bool Odbijeno { get; set; }
        public int StudentId { get; set; }
        public int UcionicaId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Ucionica Ucionica { get; set; }
    }
}
