//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutor()
        {
            this.ObimStudents = new HashSet<ObimStudent>();
            this.OcjenaStudents = new HashSet<OcjenaStudent>();
            this.OcjenaTutors = new HashSet<OcjenaTutor>();
            this.Ucionicas = new HashSet<Ucionica>();
            this.Zahtjevs = new HashSet<Zahtjev>();
        }
    
        public int TutorId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public System.DateTime DatumDodavanja { get; set; }
        public byte[] TutorSlika { get; set; }
        public byte[] SlikaOdobrenja { get; set; }
        public string NazivUstanove { get; set; }
        public double CijenaCasa { get; set; }
        public int KorisnickiNalogId { get; set; }
        public int TutorTitulaId { get; set; }
        public int RadnoStanjeId { get; set; }
        public int KontaktInfoId { get; set; }
        public int GradId { get; set; }
        public int PodKategorijaId { get; set; }
        public int StatusKorisnickoRacunaId { get; set; }
        public int SpolId { get; set; }
        public byte[] TutorTumbnail { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual KontaktInfo KontaktInfo { get; set; }
        public virtual KorisnickiNalog KorisnickiNalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObimStudent> ObimStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcjenaStudent> OcjenaStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcjenaTutor> OcjenaTutors { get; set; }
        public virtual Podkategorija Podkategorija { get; set; }
        public virtual RadnoStanje RadnoStanje { get; set; }
        public virtual Spol Spol { get; set; }
        public virtual StatusKorisnickogRacuna StatusKorisnickogRacuna { get; set; }
        public virtual TutorTitula TutorTitula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucionica> Ucionicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zahtjev> Zahtjevs { get; set; }
    }
}
