//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    
    public partial class Zahtjevi_SelectAktuelne
    {
        public int ZahtjevId { get; set; }
        public int TutorId { get; set; }
        public string Tutor { get; set; }
        public byte[] TutorTumbnail { get; set; }
        public string Predmet { get; set; }
        public double CijenaCasa { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
        public System.DateTime DatumSlanja { get; set; }
        public Nullable<int> Ocjena { get; set; }
        public bool Prihvaceno { get; set; }
        public bool Odbijeno { get; set; }
    }
}
