//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutor_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahtjev
    {
        public int ZahtjevId { get; set; }
        public System.DateTime DatumSlanja { get; set; }
        public System.DateTime DatumOd { get; set; }
        public int BrojCasova { get; set; }
        public System.TimeSpan VrijemeOd { get; set; }
        public System.TimeSpan VrijemeDo { get; set; }
        public bool Prihvaceno { get; set; }
        public bool Odbijeno { get; set; }
        public int TutorId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
